sudo: false
os: linux
dist: trusty
language: node_js
node_js:
- '8'
cache:
- directories:
  - "node_modules"
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - libavahi-compat-libdnssd-dev
install:
- npm install
- npm update
script: DEBUG='electron-installer-snap:*' yarn make:snap:64
