sudo: required
os: linux
dist: trusty
language: node_js
node_js:
- '8'
services:
- docker
cache:
- yarn: true
- directories:
  - "node_modules"
  - "$HOME/.electron"
before_install: sudo apt-get install --no-install-recommends -y libavahi-compat-libdnssd-dev
script: test/script.sh
